name: Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn install --frozen-lockfile
        working-directory: ./gallery-api/
        shell: bash

      - name: Build
        run: yarn build
        working-directory: ./gallery-api/
        shell: bash

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/750379347440/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider"
          service_account: "github-actions-service-account@gallery-challen-info.iam.gserviceaccount.com"
          
      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          source_dir: ./gallery-api/
          name: "gallery-api"
          runtime: "nodejs16"
          env_vars: OPEN_AI_KEY=YOUR_OPEN_AI_KEY

      - id: "test"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
