name: Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn install --frozen-lockfile
        shell: bash

      - name: Build
        run: yarn build-server
        shell: bash

      - name: Move node_modules
        run: |
          cp -R ./node_modules ./api2/dist/node_modules
          cp ./package.json ./api2/dist/package.json
        shell: bash

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/750379347440/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider"
          service_account: "github-actions-service-account@gallery-challen-info.iam.gserviceaccount.com"
          
      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          source_dir: ./api2/dist/
          name: "helloWorld"
          runtime: "nodejs16"

      - id: "test"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
